# Generated by Django 2.2.16 on 2022-06-04 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220604_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reviews',
            new_name='review',
        ),
    ]
